#library "TRANSLATIONS.acs"
#include "zcommon.acs"

script "Translations" ENTER
{
	CreateTranslation(99,0:255=11:15);
	CreateTranslation(98,0:159=160:167,168:207=216:223,224:255=176:191 );
	CreateTranslation(97,0:255=0:255);
}

script "ResetTranslate" (void)
{
	Thing_SetTranslation(0,97);
}

script "BurnTranslate" (void)
{
	Thing_SetTranslation(0,98);
}

script "AshTranslate" (void)
{
	Thing_SetTranslation(0,99);
}